apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    # Email берёшь из terraform output: eso_gsa_email
    iam.gke.io/gcp-service-account: eso-gsa@beneflo-gcp-project-dev.iam.gserviceaccount.com
