cluster_name   = "scalr"
gcp_project_id = "beneflo-main"
github_org       = "exitfound"
github_repo      = "scalr-gitops-infrastructure"
github_branch    = "main"
flux_version     = "2.8.5"
state_bucket     = "scalr-infrastructure-bucket"
