apiVersion: v1
kind: ServiceAccount
metadata:
  name: scalr-agent-test
  namespace: scalr-agent-test
  annotations:
    iam.gke.io/gcp-service-account: scalr-agent-gsa-test@beneflo-gcp-project-dev.iam.gserviceaccount.com
