gcp_project_id                      = "beneflo-gcp-project-dev"
scalr_hostname                      = "kitezh.scalr.io"
scalr_account_id                    = "acc-v0p7ctljql63n2eg4"
github_username                     = "exitfound"
github_secret_name                  = "github-pat"
scalr_api_token_secret_name         = "scalr-api-token"
scalr_agent_pool_token_secret_name  = "scalr-agent-pool-token"
