apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scalr-agent-token
  namespace: scalr-agent
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-sm
    kind: ClusterSecretStore
  target:
    name: scalr-agent-token
  data:
    - secretKey: token
      remoteRef:
        key: scalr-agent-pool-token
